/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // { type: 'autogenerated', dirName: '.' },
    {
      type: 'doc',
      label: '👋 Introduction',
      id: 'index',
    },
    {
      type: 'doc',
      label: '🎬 Installation',
      id: 'installation',
    },
    {
      type: 'doc',
      label: '📖 Usage',
      id: 'usage',
    },
    {
      type: 'doc',
      label: '⏳ Compilation',
      id: 'compilation',
    },
    {
      type: 'doc',
      label: '🍱 Sandbox',
      id: 'sandbox',
    },
    {
      type: 'doc',
      label: '🖥️ Origination',
      id: 'origination',
    },
    {
      type: 'doc',
      label: '🧪 Testing',
      id: 'testing',
    },
    {
      type: 'doc',
      label: '🏁 Conclusion',
      id: 'conclusion',
    },
  ],
};

module.exports = sidebars;